### ISSUE TITLE
serve a favicon

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#105]
so that this goes away:

127.0.0.1 - - [10/Aug/2014 02:40:54] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by Thor77** [comment]
What do you think about this?
Components: [FontAwesome's file-o](http://fontawesome.io/icon/file-o/), [Source Code Pro](https://github.com/adobe-fonts/source-code-pro)
![bepasty](https://cloud.githubusercontent.com/assets/4989736/10268640/10952132-6abf-11e5-8887-4305b06faeb3.png)

**Comment by ThomasWaldmann** [comment]
In big that looks quite good, but does it scale down to a favicon's size?

**Comment by Thor77** [comment]
You can't read "pasty" anymore but i think it doesn't look too terrible.
![bepasty_favicon](https://cloud.githubusercontent.com/assets/4989736/10269170/e91808d0-6ace-11e5-9451-f0b233ca4289.png)

**Comment by ThomasWaldmann** [comment]
@pguth @NotANormalNerd (and all others): what do you think?

**Comment by pguth** [comment]
I personally would prefer a B with a smaller upper body. But I am fine what @Thor77 proposes :+1:

**Comment by Thor77** [comment]
If you can suggest some font (have to be licensed with an open license, allowing remix) with a "B with a smaller upper body" i can easily change it.

**Comment by pguth** [comment]
Maybe [`Cabin Condensed`](https://www.google.com/fonts/specimen/Cabin+Condensed).

**Comment by Thor77** [comment]
![bepasty](https://cloud.githubusercontent.com/assets/4989736/10282734/9d259eac-6b7c-11e5-8523-143ad07f511d.png)
------
![bepasty_favicon](https://cloud.githubusercontent.com/assets/4989736/10282738/a0cb745a-6b7c-11e5-80e2-e440f34ff2de.png)

**Comment by ThomasWaldmann** [comment]
OK, guess we need that in the usual square sizes (16x16, 32x32, ...?).

**Comment by Thor77** [comment]
Yeah, it's an SVG-file -> you can scale it up and down like you want to.
Shall I open a pull request for this version or do you have any further suggestions?

**Comment by ThomasWaldmann** [comment]
Open a PR please (and if you easily can, please include also files for the usual favicon sizes and formats).

**Comment by ThomasWaldmann** [comment]
Fixed by:

https://github.com/bepasty/bepasty-server/commit/d93f7bdb1d7dd9746d016e585062bea5ef5b75e6
