### ISSUE TITLE
Right click → `Save as` dysfunctional for attachments

### ISSUE THREAD

**Issue by perguth** [bepasty/bepasty-server#127]
Will yield a HTML file instead of the attached document. This goes for the "filename link" on the left as well as the action buttons on the right (`display`, `download`, ...).

**Comment by ThomasWaldmann** [comment]
I had a similar issue:

Wanted to copy the "download url" from the download button on the item view page to use it with wget: doesn't work.

**Comment by ThomasWaldmann** [comment]
buttons ﬁxed by #218.

**Comment by ThomasWaldmann** [comment]
list view:

the filename links to the "rich" display view, so save-as is expected to save html, no bug here.

but if one clicks save-as on the download button to the right, one gets the correct file.

so, guess this is as good as it gets.
