### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Thor77** [bepasty/bepasty-server#136]
Hey,
I have some questions regarding your tests:
- why are test-files placed between other prod-files?
- why are you not using any continous integration service (like travis)?
- why is there no coverage-checking? (seems like tests are quite incomplete atm)

I would investigate some time to write some more tests, but i would suggest to use some testing-description-framework (like [Lettuce](http://lettuce.it/) or [Behave](http://pythonhosted.org/behave/)) for better overview what's exactly happening (especially for selenium-tests).

**Comment by NotANormalNerd** [comment]
Test have been taken over from the initial project.
We have not really cared about test by now 
but would of course be happy if someone would introduce them.

**Comment by ThomasWaldmann** [comment]
@Thor77 these are all good questions / reasonable suggestions. It's just waiting for someone to do it. :)

I'ld like to stay with py.test for the Python tests, though.

**Comment by ThomasWaldmann** [comment]
we use travis-ci now.

**Comment by ThomasWaldmann** [comment]
all tests are under `src/bepasty/tests/` now.

so I guess the main issues have been addressed meanwhile.
