### ISSUE TITLE
permissions don't work

### ISSUE THREAD

**Issue by t2b** [bepasty/bepasty-server#143]
after commit https://github.com/bepasty/bepasty-server/commit/734c64a870b92b28475db1d6ddbbc77743d054b0 permissions for read,create,... don't work.
I can't create any new pastes or access existing pastes.

**Comment by ThomasWaldmann** [comment]
@Thor77 can you have a look?

**Comment by Thor77** [comment]
oh, damnit. i didn't check, if flaskg.permissions is used for some important stuff (tests ftw :P)
