### ISSUE TITLE
Pretty rendering of image list items

### ISSUE THREAD

**Issue by rixx** [bepasty/bepasty-server#148]
If a list of items consists of only pastes with an `image/*` content type, it would be nice to render them as an album of images, or at least a list of previews.

**Comment by ThomasWaldmann** [comment]
yes, but don't overdo this, just something simple. it's a pastebin, not an album app.

**Comment by ThomasWaldmann** [comment]
first do #177.

**Comment by ThomasWaldmann** [comment]
Update: I implemented #177 (see PRs) and am now starting to work on this issue.

For the "pretty" part of this, I likely will need some help (html, css, js) ...

**Comment by ThomasWaldmann** [comment]
I added a rather minimal solution to #271 - it now displays the thumbnails in a separate column.

**Comment by ThomasWaldmann** [comment]
Merged the "carousel view" for image list items. It's neither feature rich, nor pretty, PRs to improve it are welcome.
