### ISSUE TITLE
handle protocol errors

### ISSUE THREAD

**Issue by dansan** [bepasty/bepasty-server#149]
A header key (Maxlife-Value) without a value caused an (incomplete) HTTP "500 Internal Server Error" page, while I think it should be "400 Bad Request" (as it is an error of the client).

**Comment by ThomasWaldmann** [comment]
i checked the code (rest api as well as web api) and it always uses `.get(key, default)` for these, so I guess this was already fixed a while ago and does not result in 500 any more.

also, as we define a default, it is now legal to omit these values.
