### ISSUE TITLE
Better explain permission setup

### ISSUE THREAD

**Issue by Marwe** [bepasty/bepasty-server#151]
Hi, 
I just installed bepasty, and don't get the permissions working properly. I think at least the documentation needs some more explanation. Here is what I understood and tried so far:

* README.rst: there are permissions, you should use them carefully

During setting up bepasty (according to docs/source/install-tutorial.rst): *Copy bepasty/config.py*, but no details about permissions (points one to the config settings).
In the config file itself there are some explanations:

> #: logged-in users may get more permissions.
> #: a user may have a login secret to log in and, depending on that secret,
> #: he/she will get the permissions configured here.
> #:
> #: you can use same secret / same permissions for all privileged users or
> #: set up different secrets / different permissions for each user.
> #:
> #: PERMISSIONS is a dict that maps secrets to permissions, use it like:
> #:
> #: ::
> #:
> #:     PERMISSIONS = {
> #:         'myadminsecret': 'admin,list,create,read,delete',
> #:         'uploadersecret': 'create,read',
> #:     }

So, from that:
* there are no usernames, only 'secrets'
* the *secrets* are used to identify permissions for users, so are used like usernames, username==secret/password. 

This confuses at least me, maybe I am too used to user+pass auth. The concept is OK, but if you talk about both users and secrets, then an explanation might be needed (or different wording maybe: account, credential, authorization, access permission, service password, pass, warrant, permission(-password), passphrase, secret).

From  *docs/source/user.rst* 

> To log in, you need to know credentials - ask the admin who runs the site.
> 
> The site admin can assign permissions to login credentials (and also to the anonymous, not logged-in user): [...]

I am the admin, and if I get asked, I do not know how ;). I set some accounts up in the config with `PERMISSIONS = { 'thecredential': 'create,read', }`, but cannot see any permission change after using it on the main page. What else is necessary, am I missing something?

 Thanks for looking at this.

**Comment by Marwe** [comment]
BTW, I run this non-public, behind htaccess authentication. That auth could also be used for bepasty? Documentation is a bit sparse for it, but found some references.

**Comment by ThomasWaldmann** [comment]
bepasty does not have a user account database and it does not know about usernames.

the secrets are the only authorization thing that exists in bepasty.

the users of bepasty (meaning "the people who use bepasty", not that there are user accounts) either know a secret to enter or they don't.

if they enter a valid secret, they get the permissions related to that secret (see config), otherwise they have the default permissions.

as ever, you can put some htaccess webserver authentication in front of bepasty, but this is less flexible and more work to manage.

**Comment by ThomasWaldmann** [comment]
if you do not see a change after entering a valid secret, it maybe means that you have not restarted the bepasty webapp process after changing the configuration.

**Comment by Marwe** [comment]
Thanks for the explanation, would fit the documentation (just as you gave it here, very clear).
