### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by valholl** [bepasty/bepasty-server#152]
I notice that the latest release of bepasty on pypi (and the latest release tag) was in 2014, and in the meanwhile there has been some developement in the git repo.

Additionally, the gpg signature published on pypi has been made with an expired (sub)key, resulting in an error when verifying that contributes to a feeling of abandoned project that, in my opinion, is not justified.

Could it be time for a new pypi release?

Thanks in advance

**Comment by ThomasWaldmann** [comment]
Yeah, you're right, we should do a new release.

Can you help with any of these tickets?

https://github.com/bepasty/bepasty-server/milestone/5

**Comment by ThomasWaldmann** [comment]
closing this, next release is tracked by that milestone.

i don't see a gpg signature on pypi.org, but if i do next release, i'll use my current key anyway.
