### ISSUE TITLE
support asciinema player?

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#175]

**Comment by isaaclw** [comment]
I was getting a 404 with the asciinema-player.js and asciinema-player.css file missing.
So I came here to try to find out where the file is. When I look at the git repo the paths in the commit point to:
`src/bepasty/static/app/css/asciinema-player.css` and `src/bepasty/static/app/js/asciinema-player.js`

These two files don't exist exist in the final merge though. Somewhere between 0a5f6e6de52c928575c85d1330bb73d85ae154fc and HEAD on the branch these files were... removed?

Anyway, I just manually pulled the file from the commit, I was just very confused on what happened on github.

I guess ignore this if it's not worth your time to explain it to me.

**Comment by ThomasWaldmann** [comment]
The files come from the xstatic-asciinemaplayer (or so) package.
