### ISSUE TITLE
docs on rtfd do not build

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#191]
also, i do not have admin access there, so i can't check the settings.

**Comment by ThomasWaldmann** [comment]
@jarus ^

**Comment by ThomasWaldmann** [comment]
@jarus https://readthedocs.org/projects/bepasty-server/builds/

(or just give me access, so i can fix it, my username there is "thomaswaldmann")

**Comment by ThomasWaldmann** [comment]
guess it is quicker to set up a new rtfd site than getting a response from jarus. :-|

**Comment by ThomasWaldmann** [comment]
I can't setup a new site on rtfd because "that project has already been imported".

So, @jarus, please add me as a maintainer on rtfd.

**Comment by ThomasWaldmann** [comment]
my user id at rtfd is "thomaswaldmann".

**Comment by jarus** [comment]
Sorry for the huge delay. You should now have admin rights in the readthedocs project.

**Comment by ThomasWaldmann** [comment]
It crashes when installing the requirements:
```
Searching for xstatic-jquery
Processing XStatic-jquery-ui-1.12.1.1.tar.gz
Writing /tmp/easy_install-YNnq_Y/XStatic-jquery-ui-1.12.1.1/setup.cfg
Running XStatic-jquery-ui-1.12.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YNnq_Y/XStatic-jquery-ui-1.12.1.1/egg-dist-tmp-xzZwTR
Extracting XStatic_jquery_ui-1.12.1.1-py2.7.egg to /home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/latest/lib/python2.7/site-packages
XStatic-jquery-ui 1.12.1.1 is already the active version in easy-install.pth

Installed /home/docs/checkouts/readthedocs.org/user_builds/bepasty-server/envs/latest/lib/python2.7/site-packages/XStatic_jquery_ui-1.12.1.1-py2.7.egg
error: The 'xstatic-jquery' distribution was not found and is required by xstatic-jquery-ui, bepasty
```

**Comment by ThomasWaldmann** [comment]
It searches for `xstatic-jquery` and finds `xstatic-jquery-ui`. WTF?

**Comment by ThomasWaldmann** [comment]
it needed 2 fixes to make the docs build on rtfd:

e347822985ed313ad3f89ea14546e14d68b712b6

5887c9e2050e47564ba87f55a362d9fe0a34a10e
