### ISSUE TITLE
Editing the content-type or filename of an uploaded file via CLI

### ISSUE THREAD

**Issue by cesardv** [bepasty/bepasty-server#194]
So it looks like bepasty-object set CLI can only set/edit the `locked` and `complete` metadata flags?

Is this so? Is there any way to (via REST, or manually on the server) change the content-type or filename of an uploaded file?

**Comment by ThomasWaldmann** [comment]
Yes, this is what the current code can do.

bepasty-object is mostly stuff useful for the admin (not: the user) of a bepasty site.

To be useful for a user, functionality would be needed to be exposed over the web interface and the rest api.

**Comment by cesardv** [comment]
Hi Thomas, thanks for the fast reply, but I'm confused by your first sentence... So can the admin edit the content-type using bepasty-object or some other method? Or it is not possible?

**Comment by ThomasWaldmann** [comment]
Not with the current code.

**Comment by cesardv** [comment]
Ah ok cool, thanks for clearing that up. If I have some tie today, I'll try and take a look at their code and see if I can perhaps send you a pull request for `bepasty-object set` ... do you think it'd be difficult to add that functionality to `bepasty-object`? I'm a little rusty on my python

**Comment by ThomasWaldmann** [comment]
Guess that shouldn't be too hard.

**Comment by ThomasWaldmann** [comment]
see PR #240

**Comment by ThomasWaldmann** [comment]
fixed.
