### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by dausruddin** [bepasty/bepasty-server#210]
Or at least screenshots?

**Comment by ThomasWaldmann** [comment]
There is no publicly-writable installation as far as I know.

But I run a pastebin with it for own usage, you can see it there:

https://paste.thinkmo.de/

For privacy reasons, you can not list the contents of the pastebin, but here are some example items:

https://paste.thinkmo.de/MPi3kUYr
https://paste.thinkmo.de/JuiYcaDE
https://paste.thinkmo.de/srbJgYp6
https://paste.thinkmo.de/HdttQtyR
https://paste.thinkmo.de/XsVyoNQm
https://paste.thinkmo.de/xsFUCKL7
https://paste.thinkmo.de/f9fCLoug

**Comment by dausruddin** [comment]
Thanks a lot!
