### ISSUE TITLE
QR code should generate URL from config (fqdn)

### ISSUE THREAD

**Issue by Marwe** [bepasty/bepasty-server#213]
Thank you for the QR code option, a very nice feature!

Since I have a reverse proxy in front, my QR code URLs initially point to
http://localhost:4444/hash

Manual solution: I can manually copy the URL from the browser and replace the string on the text input on the page, and the QR code will adapt.

Expected behaviour: the QR code should show the internet-wide valid URL based on fqdn of the bepasty instance.

Would it be possible to use the SITENAME variable from config to generate the URL for the text field?

> #: name of this site (put YOUR bepasty fqdn here)
> SITENAME = 'bepasty.domain.tld'

Maybe then the APP_BASE_PATH and PrefixMiddleware needs to be taken into account, too.

BTW, for FF there is this nice addon to create QR codes (offline, privacy preserving): 
https://github.com/rugk/offline-qr-code

**Comment by ThomasWaldmann** [comment]
thanks for the suggestion. for usage behind a proxy, it needs to deal with:
- protocol
- fqdn
- port

**Comment by ThomasWaldmann** [comment]
I also have a reverse proxy setup and I do not see any problem with the QR url.
Guess you need to set some env vars in your web server configuration.

**Comment by ThomasWaldmann** [comment]
If that is not enough, there is also the `ProxyFix` middleware in werkzeug.

**Comment by ThomasWaldmann** [comment]
No reply, closing...
