### ISSUE TITLE
update AUTHORS

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#241]
@OGAWAHirofumi should add himself there, please.

Anybody else missing? Just do PRs and add yourself as *you* want it, please.

**Comment by ThomasWaldmann** [comment]
If anyone else wants to update, do it ASAP, will release 0.6.0 soon.

**Comment by ThomasWaldmann** [comment]
guess that is all for now.

**Comment by ThomasWaldmann** [comment]
@dasJ maybe?

**Comment by dasJ** [comment]
Oof
