### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by Chevek** [bepasty/bepasty-server#266]
Hello,

I'm using bepasty-server as part of Freedombox in Debian ( https://freedombox.org/ ).
I'm french and I would like to use bepasty as a collectiv storage for files with my neighbours. For that purpose, I need to translate it in french. I did not found any support for i18n to help translation, so I just changed the files on my server.
Please consider adding i18n support to bepasty.

I attached the changes I've made to translate the UI in french against current master:
[french.txt](https://github.com/bepasty/bepasty-server/files/5978624/french.txt)

Best regards

**Comment by ThomasWaldmann** [comment]
Not sure I want to implement this myself, but if someone makes a good PR for this I'll consider merging it.

It of course can't just be patched like done in the patch in the top post, but there needs to be some infrastructure in the code, dynamically switching the web UI language depending on the user's preference.

As bepasty does not have user profiles, we can only use the user's browser preference announced in the `Accept-Language` http header.

Keywords:
- babel
- transifex (optional, more comfortable for translators, but maybe not needed to that few strings)

**Comment by ThomasWaldmann** [comment]
Not planned (as far as I am concerned).
