### ISSUE TITLE
Thumbnail displays broken image in list view

### ISSUE THREAD

**Issue by luckman212** [bepasty/bepasty-server#278]
Not sure what my issue is here but, even if pasting a valid image, on the list view the Thumbnail is broken:

![CleanShot 2021-10-04 at 09 28 53](https://user-images.githubusercontent.com/1992842/135860017-af86fdd4-13f2-4062-8e68-39d37a8dc4a1.png)

The image seems to be "ok" - if you click Display/detail view:
![image](https://user-images.githubusercontent.com/1992842/135859824-3ebc2978-ce9e-4316-bb6d-060e8b2e48ce.png)

When navigating directly to the eg `/XoPyMpQx/+thumbnail` endpoint, In Chrome's console, this error is displayed, not sure if it matters:
![image](https://user-images.githubusercontent.com/1992842/135859707-0f709920-0c53-4c04-8307-3b0a3b143c2c.png)

**Comment by ThomasWaldmann** [comment]
501 is "not implemented".

did you install bepasty with the optional `pillow` support? Like `pip install bepasty[pillow]`.

**Comment by luckman212** [comment]
This is what I've got:

```shell
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

# pip list
Package                    Version             Location
-------------------------- ------------------- ----------------------
bepasty                    1.0.1.dev9+g8f4c23f /home/bepasty/repo/src
click                      8.0.1
Flask                      2.0.1
gevent                     21.8.0
greenlet                   1.1.2
gunicorn                   20.1.0
itsdangerous               2.0.1
Jinja2                     3.0.1
MarkupSafe                 2.0.1
Pillow                     8.3.2
pip                        20.3.4
pkg-resources              0.0.0
Pygments                   2.10.0
setuptools                 44.1.1
Werkzeug                   2.0.1
wheel                      0.34.2
XStatic                    1.0.2
XStatic-asciinema-player   2.6.1.1
XStatic-Bootbox            5.5.1.1
XStatic-Bootstrap          4.5.3.1
XStatic-Font-Awesome       4.7.0.0
XStatic-jQuery             3.5.1.1
XStatic-jQuery-File-Upload 10.31.0.1
XStatic-jquery-ui          1.12.1.1
XStatic-Pygments           2.9.0.1
zope.event                 4.5.0
zope.interface             5.4.0
```

**Comment by ThomasWaldmann** [comment]
Maybe try an older pillow. That used to work.

Maybe filing an issue in pillow's issue tracker could also help.

**Comment by luckman212** [comment]
Thanks- Any particular pillow version that is known to work?

**Comment by luckman212** [comment]
I tried to install the last 7.x version, but it fails to install w. Python3.9. Seems the oldest version I can install there is `8.0.0`.

So I tried `pip install Pillow==8.0.0` and restarted everything.
Sadly, did not fix the broken thumbnails. Guess this is a dead end & needs to be opened with https://github.com/python-pillow/Pillow/issues ?

**Comment by ThomasWaldmann** [comment]
Yeah, please open an issue there. Maybe the code has some incompatible change or bepasty uses it in a problematic way.

**Comment by ThomasWaldmann** [comment]
I tried this right now and it worked great for JPEGs, but not for PNG (I could reproduce your issue for these).
