### ISSUE TITLE
S3 storage support

### ISSUE THREAD

**Issue by NoverNobida** [bepasty/bepasty-server#279]
Is there any plan of supporting S3 storage?

**Comment by ThomasWaldmann** [comment]
No. There is a branch with another (unmaintained) storage backend, in case that's interesting.

**Comment by ThomasWaldmann** [comment]
https://github.com/bepasty/bepasty-server/tree/ceph-storage (back then, 8y ago, there was some idea to support ceph - but there was no active maintainer for it and IIRC also nobody used it, so it was dropped from main branch)

if one runs a pastebin for a relatively small group of people (not public for everybody on the internet), storage space and fs requirements are rather low. often stuff is only short-term use and expires after short, often it's just some text snippets, not a large volume of data.

**Comment by NoverNobida** [comment]
Is there any way to change the time zone?

**Comment by ThomasWaldmann** [comment]
You mean for the upload and expiry timestamps?

No. There are no user accounts/profiles, thus the server does not know the user's timezone. It's all in UTC.

(not really related to this issue's topic, thus i will delete these comments later)

**Comment by ThomasWaldmann** [comment]
No S3 supported planned.
