### ISSUE TITLE
Network(s)

### ISSUE THREAD

**Issue by blokdk** [bepasty/bepasty-server#280]
Dear readers,
I have several problems with the use of Bepasty. 
I came across its existence reading a Dutch LinuxMagazine where the installation on a raspberry 3 A was described. After performing the steps and cleaning up some mistakes nothing worked. When I installed the raspi3B that I used was connected to two different networks; a cabled and a wireless, in two different IP-domains. The two routers in my local network have been working fine for years now. So, I am not aware of any misconfiguration.
Only after extending the hosts file on the cabled machines could I contact the bepasty server in the browser. These cabled machines, laptops, also have a wifi interface. So I adapted the hosts file for the wifi connection as well. 

But the pure wifi devices,(android) tablets and phones will not work in my local network.

As I read nothing on the intended networks in the documentation I ask for advice.

BTW: please be more explicit about what is described as an URL, please provide an image.

Greetings,
pablok

**Comment by ThomasWaldmann** [comment]
It sounds like you have a networking or DNS issue (if editing the hosts file fixes the issue, it is likely a DNS issue and you work around it by resolving via the hosts file).

About bepasty docs: their scope is bepasty, not general network or server administration / configuration.
So, if you have a DNS or webserver issue, please read the respective docs.

https://en.wikipedia.org/wiki/URL
