### ISSUE TITLE
bepasty is not yet compatible with werkzeug 3

### ISSUE THREAD

**Issue by ThomasWaldmann** [bepasty/bepasty-server#312]
due to breaking changes in werkzeug, bepasty does not work with werkzeug >= 3.0 yet.

if your installation broke, the fix is to downgrade werkzeug: `pip install 'werkzeug<3'` (e.g. 2.3.8 works).

**Comment by ThomasWaldmann** [comment]
workaround in #311 merged.

**Comment by valholl** [comment]
A Debian maintainer working on werkzeug 3 provided a simple patch:
[0006-src-Use-urllib.parse.quote-instead-of-werkzeug.url_q.patch.txt](https://github.com/bepasty/bepasty-server/files/14001894/0006-src-Use-urllib.parse.quote-instead-of-werkzeug.url_q.patch.txt) which would make bepasty work with both old and new werkzeug: more details and attributions are at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061237

**Comment by ThomasWaldmann** [comment]
@valholl Thanks for providing the links, I applied the patch, will be in bepasty 1.2.1 release.

**Comment by aither64** [comment]
@ThomasWaldmann I'm maintaining bepasty package for NixOS and since NixOS recently updated to werkzeug 3, bepasty is currently broken. Do you have any plans to release 1.2.1? The patch from #319 seems to be sufficient to make it work.

**Comment by ThomasWaldmann** [comment]
Working on a release...

**Comment by ThomasWaldmann** [comment]
@aither64 released 1.2.1, see pypi or github releases!

**Comment by aither64** [comment]
Perfect, thanks!
